[project]
name = "warehouse-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "faker>=38.2.0",
    "fastapi>=0.123.10",
    "pandas>=2.3.3",
    "uvicorn[standard]>=0.38.0",
]
